# Generated by Django 4.0.1 on 2023-04-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvideo', models.FileField(null=True, upload_to='captions/')),
            ],
        ),
    ]
