# Generated by Django 4.0.1 on 2023-04-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_captionvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptionVideo',
        ),
    ]
